server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: backend

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

security:
  jwt:
    expiration-seconds: 86400
    issuer: nexo-finance
